### ISSUE TITLE
Typo in "Constituency" key name

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/omi-parliament-endpoint#1]
Hi,

I found a typo for `constituency` key in every MP's data.
![screen shot 2015-09-14 at 12 15 33 pm](https://cloud.githubusercontent.com/assets/6995089/9842896/7e7f267e-5ada-11e5-9859-1d58a03751cb.png)

**Comment by mapmeld** [comment]
oops! ok I'll patch this up soon
