### ISSUE TITLE
MP-IDs mismatch for a same person

### ISSUE THREAD

**Issue by phyominthu** [MyanmarAPI/omi-parliament-endpoint#2]
Hi,

I found IDs for the same MP mismatch in different endpoints. I'll show you example with an MP named "U Ohn Tin".

**See his ID at `/members` endpoint**
![screen shot 2015-09-14 at 1 42 09 pm](https://cloud.githubusercontent.com/assets/6995089/9844179/17b97b58-5ae7-11e5-82e7-50b022f12f36.png)

**See his ID at `/questions` endpoint**
![screen shot 2015-09-14 at 1 48 31 pm](https://cloud.githubusercontent.com/assets/6995089/9844213/63df2c80-5ae7-11e5-8622-6d4da39526c2.png)

**See his ID at `/motions` endpoint**
![screen shot 2015-09-14 at 1 50 21 pm](https://cloud.githubusercontent.com/assets/6995089/9844236/95bdd382-5ae7-11e5-9d6f-cc90a3370b36.png)

**Comment by mapmeld** [comment]
you're right... let me take a look at this

**Comment by mapmeld** [comment]
thanks! this is all fixed now:
- members: https://raw.githubusercontent.com/MyanmarAPI/omi-parliament-endpoint/gh-pages/members/U%20Ohn%20Tin.json
- questions: https://raw.githubusercontent.com/MyanmarAPI/omi-parliament-endpoint/gh-pages/questions/U%20Ohn%20Tin.json
- motions: https://raw.githubusercontent.com/MyanmarAPI/omi-parliament-endpoint/gh-pages/motions/U%20Ohn%20Tin.json

if you have any questions, we have the original data in TSV format (in this repo's source folder)

**Comment by phyominthu** [comment]
The API is still returning mismatch IDs. @mapmeld

**Comment by mapmeld** [comment]
@phyominthu can you send specific examples?  Each item has an ID

The MPID for U Ohn Thin: UPMP-01-0113

One motion asked by this MP has this ID: UP-01-04-027

One question asked by this MP has this ID: UPQ-01-02-114

**Comment by phyominthu** [comment]
I checked source TSVs. I think I have found where the error is occurring. The **API** shows the ID correctly at `/members` endpoint. But in `/questions` and `/motions`, it shows ID and and questions/motions of the MP who is above the MP we are looking for. The **API** is pointing at the different MP.

**Dr. Aye Maung**'s questions and MP-ID show up when I search for **U Ohn Tin** 
![screen shot 2015-09-14 at 3 50 35 pm](https://cloud.githubusercontent.com/assets/6995089/9846526/b60ad408-5af8-11e5-9e2c-bf422a2c350d.png)

**U Nyunt Tin**'s motions and MP-ID show up when I search for **U Ohn Tin** 
![screen shot 2015-09-14 at 3 57 48 pm](https://cloud.githubusercontent.com/assets/6995089/9846629/65b3fc86-5af9-11e5-9c58-485336d09e1f.png)

**Comment by mapmeld** [comment]
@phyominthu I just found out that the old data was cached in the MaePaySoh API.  We should have the data updated there very soon

**Comment by phyominthu** [comment]
Now they're correct. Thanks!
